-- Update notifications table to include new service request notification types
ALTER TABLE notifications 
MODIFY COLUMN notification_type ENUM(
    'TASK_ASSIGNED', 
    'STATUS_UPDATE', 
    'DOCUMENT_UPLOADED', 
    'DOCUMENT_VERIFIED', 
    'DOCUMENT_REJECTED', 
    'DEADLINE_REMINDER', 
    'STAFF_ASSIGNED', 
    'TASK_COMPLETED', 
    'TASK_ACKNOWLEDGED', 
    'SYSTEM', 
    'EMAIL', 
    'MESSAGE_RECEIVED',
    'LEAD_ASSIGNED',
    'NEW_LEAD_CREATED',
    'LEAD_CONVERTED',
    'SERVICE_REQUEST_CREATED',
    'SERVICE_REQUEST_STATUS_CHANGED',
    'SERVICE_REQUEST_ASSIGNED',
    'SERVICE_REQUEST_REJECTED',
    'SERVICE_REQUEST_CANCELLED',
    'SERVICE_REQUEST_CONVERTED_TO_TASK'
) NOT NULL;
